Version 0.9.4 etc/common.cfg - Log levels added.   Use 	logThis "msg" "LOGLEVEL"   for loglevels. Defaults to no log level (so everything still works without defining a LOGLEVEL).   Currently implemented LOGLEVELS: 	- W|w = warning 	- D|d = debug - Disabled time tracking of scripts (did not work) -
sbin/DHTXXD
- wait-for-read loop updated.
  If no read from DHT22, function will wait 'sleep' sec(s) and try the read again for maximum of 'iterMax' times after which it will produce a PushBullet notification

etc/errors.cfg
- added errorlevel 19 for DHTXXD

temperature-monitor
- Added debug for read errors from DHT22.
  If no read, function will loop through until read succeeds or 'maxIters' reached. Also logs error (forced for now, will change this to obey logging-variable in the future).

Modified PushBullet messaging script
Basically everything works as before. Behind the scenes the script now logs more and the logs make more sense now. Common files common.cfg and shellcommands.cfg needed to be updated to enable this (some functionality added).

Removed [forced] extra debugging output.

Fixed typos, bugs, etc.

diff --git a/temperature-monitor b/temperature-monitor
--- a/temperature-monitor
+++ b/temperature-monitor
@@ -3,9 +3,9 @@ strtTme=$(date +%s.%N)
 
 #################################
 #
-#  version: 0.0.1.0013
+#  version: 0.0.2.0003
 #  date: 27.11.2018
-#  mod': 03.02.2019
+#  mod': 05.02.2019
 #  Copyright Tommi Nikkilae 2018
 #  url: http://f8.oire.fi/blog (techy things)
 #  url: http://f8.oire.fi/ (my photos)
@@ -102,6 +102,15 @@ strtTme=$(date +%s.%N)
 	elif [ ! -z "$1" ]; then
 		tempLowLimit=$1
 	fi
+#
+
+	sleep="1.5"
+	maxIters=10
+	res="0"
+#
+#	via .conf:
+#	OID=".1.3.6.1.2.1.25.1.11.1"
+#	mySensor1="/sys/bus/w1/devices/28-03170422eaff"
 #  This will not work as bc has no add-leading-zero-if-missing operative.
 #  tempRecoveryLimit=$(${SH_ECHO} "scale=1;$tempLowLimit+$tempRecoveryThreshold"|bc -l)
 #  We'll use
@@ -122,34 +131,52 @@ strtTme=$(date +%s.%N)
 #[ -z "$1" ] && usage
 #[ something "$1" ] || err "1" "$1"
 
-OID=".1.3.6.1.2.1.25.1.11.1"
-res="0"
-mySensor1="/sys/bus/w1/devices/28-03170422eaff"
-
 tempRaw=$(${SH_GREP} "t=" $mySensor1/w1_slave|${SH_CUT} -d "=" -f 2)
 #in=$(getDHTread "temp")
+
+i=0
 in=$(${SH_DHT}|${SH_CUT} -d " " -f 2)
+
+while [ -z "$in" ]; do
+	if [ "$i" -eq "$maxIters" ]; then
+		break
+		exit 1
+	fi
+
+#	[ -z "$in" ] && ${SH_SLEEP} $sleep || break
+	if [ -z "$in" ]; then
+		loggingTmp=$logging
+		logging=1
+		iterSecs=$(echo "scale=0; ($i*$sleep)/1"|bc -l)
+		logThis "Read error from DHT22. Error count: $i of $maxIters [$iterSecs sec(s)]). Got result (\$in) '$in'." "D"
+		logging=$loggingTmp
+		${SH_SLEEP} $sleep
+	else
+		break
+		exit 1
+	fi
+	in=$(${SH_DHT}|${SH_CUT} -d " " -f 2)
+	(( i++ ))
+done
+
 if [ $(${SH_ECHO} "$in>$tempLowLimit" | bc) -eq 0 ]; then
 	logThis "Temperature is below $tempLowLimit"$'\xc2\xb0'"C ($in"$'\xc2\xb0'"C)!"
 	err 20 "$in"$'\xc2\xb0'"C" "$tempLowLimit"$'\xc2\xb0'"C"
-elif [ -e "$trckErr" ]; then
-	echo "Above. The file exists."
-	if [[ $(${SH_ECHO} "$in<$tempRecoveryLimit" | bc) -eq 0 ]]; then
-#	if [[ $(${SH_ECHO} "$in>$tempRecoveryLimit" | bc) -eq 0 ]]; then
 
-	# we must assume the temperature was below threshold before
-	# if we want to get notified when it was and is no more
-	# So, let's test if we have an error file (this is true
-	# if notification was sent previously)
+# we must assume the temperature was below threshold before
+# if we want to get notified when it was and is now no more
+# So, let's test if we have an error file (this is true
+# if notification was sent previously)
+elif [ -e "$trckErr" ]; then
+	if [[ $(${SH_ECHO} "$in<$tempRecoveryLimit" | bc) -eq 0 ]]; then
 		pushTemp=$push
 		push=1
 		msg="Temperature has recovered and is now: $in"$'\xc2\xb0'"C (alert threshold: $tempRecoveryLimit"$'\xc2\xb0'"C)."
 		${SH_RM} -f $trckErr # || err "4" "$timeDiff"
 		ntfy "$msg"
-		logThis "Temperature recovered to above $tempRecoveryLimit"$'\xc2\xb0'"C ($in"$'\xc2\xb0'"C)! A notify was sent."
+		[ "$debug" -gt "0" ] && logThis "Temperature recovered to above $tempRecoveryLimit"$'\xc2\xb0'"C ($in"$'\xc2\xb0'"C)! A notify was sent."
 		push=$pushTemp
 		${SH_RM} -f $trckErr # || err "4" "$timeDiff"
-		## [ -e "$trckErr" ] && logThis "The thing is still here!" || logThis "I finally destroyed the thing!"
 		# See, the thing is that scriptEnd() will do a push (again) and then create a lock file
 		# That will loop this option forever and ever when temperature "has recovered". We need to
 		# notify of this recovery *only once*. To do this, we will kill the script here.
@@ -157,20 +184,19 @@ elif [ -e "$trckErr" ]; then
 		exit 0
 	else
 		msg="Temperature has recovered and is now: $in"$'\xc2\xb0'"C. This however is nothing new. I will not notify anyone of this. See: $trckErr"
-		logThis "$msg"
+		[ "$debug" -gt "0" ] && logThis "$msg"
 		# see above: we need to kill the script here and now.
 		# exit 0
 	fi
 else
 	msg="Temperature is above the notify treshold limit of $tempRecoveryLimit"$'\xc2\xb0'"C: $in"$'\xc2\xb0'"C)! No previous notification? Then this is not a recovery and no notification should be sent this time, either. [Based on existing '$trckErr' file.]"
-	logThis "$msg"
+	[ "$debug" -gt "0" ] && logThis "$msg"
 fi
 
 msg="Temperature (in): $in"$'\xc2\xb0'"C."
 #${SH_ECHO} "My limits are low: $tempLowLimit"$'\xc2\xb0'"C and recovery: $tempRecoveryLimit"$'\xc2\xb0'"C!"
 #${SH_ECHO} $msg
-[ "$1" == "-p" ] && ${SH_ECHO} $msg
-
+logThis "$msg"
 #################################
 #
 # End the script
