Stability updates

diff --git a/sbin/DHTXXD b/sbin/DHTXXD
--- a/sbin/DHTXXD
+++ b/sbin/DHTXXD
@@ -1,11 +1,12 @@
 #!/bin/bash
 strtTme=$(date +%s.%N)
+myNameIs=${0##*/}
 
 #################################
 #
-#  version: 1.2.2.0005
+#  version: 1.2.3.0002
 #  date: 25.05.2018
-#  mod': 05.02.2019
+#  mod': 11.02.2019
 #  Copyright Tommi Nikkilae 2018-2019
 #  url: http://f8.oire.fi/blog (techy things)
 #  url: http://f8.oire.fi/ (my photos)
@@ -55,9 +56,17 @@ strtTme=$(date +%s.%N)
 #
 #  /usr/local/etc/common.cfg
 #
-	myPathIs=${0%/*}
-	[ -f "$myPathIs/etc/common.cfg" ] && commonFile="$myPathIs/etc/common.cfg" || commonFile="/usr/local/etc/common.cfg"
-	. "$commonFile"
+	commonFile="/usr/local/etc/common.cfg"
+#	[ -f "$myPathIs/etc/common.cfg" ] && commonFile="$myPathIs/etc/common.cfg" || commonFile="/usr/local/etc/common.cfg"
+	if [ -f "$commonFile" ]; then
+		if ! . "$commonFile"; then
+			logger "$myNameIs :: Reading of common file $commonFile failed. Die."
+			exit 1
+		fi
+	else
+		logger "$myNameIs :: Common file $commonFile not found. Die."
+		exit 1
+	fi
 #
 #  If you want errors to kill the script, use
 	errKills=1
@@ -90,7 +99,7 @@ strtTme=$(date +%s.%N)
 #
 #  Define the minimum time between push notifications
 #
-	minNotifyIntervalInMinutes=15
+	minNotifyIntervalInMinutes=86400
 #
 #################################
 
@@ -99,13 +108,20 @@ strtTme=$(date +%s.%N)
 #  Set some more variables here if needed
 #	myVar1=foo
 #	myVar2="Lorem ipsum."
-	sleep=1.5
+	sleep="2.2"
+	dht22LockFile="/lockdir/dht22LockFile"
+#
 #
 #################################
 
 #################################
 #
 #  Functions begin here
+#
+	removeLock() {
+		logThis "DHT22 lock ($dht22LockFile) remove requested..." "T" "$FUNCNAME"
+		[ $(${SH_RM} -f $dht22LockFile & > /dev/null) ] && err "2" "$dht22LockFile" || logThis "Lock file $dht22LockFile removed." "D"
+	}
 #
 #  Functions end. Your code starts here.
 #
@@ -115,36 +131,63 @@ strtTme=$(date +%s.%N)
 #
 # Actual code part goes here...
 #
-
-dht22LockFile="/lockdir/dht22LockFile"
-
 # Check for our lock file;
 # If exists, wait: another script is accessing DHT22
-
-i=0
-maxWaitIters=10
-
-while [ -f "$dht22LockFile" ]; do
-	logThis "DHT22 busy, waiting ($i/$maxWaitIters)..."
-	${SH_SLEEP} $sleep;
-	(( i++ ))
-	if [ "$i" -eq "$maxWaitIters" ]; then
-		err 19 "$myNameIs, $i tries"
-		break
-	fi
-done
-
+#
+	i=0
+	maxWaitIters=15
+#
+	logThis "Checking if DHT22 is available..." "T"
+	while [ -f "$dht22LockFile" ]; do
+		logThis "DHT22 busy, waiting for $sleep sec(s) for re-read ($i/$maxWaitIters)..." "D"
+		${SH_SLEEP} $sleep;
+		(( i++ ))
+		if [ "$i" -eq "$maxWaitIters" ]; then
+			err 19 "$myNameIs" "$i"
+			break
+		fi
+	done
+#
+	logThis "Check done. Errors were logged if any." "T"
+	logThis "Creating lock file for DHT22 read..." "T"
+#
 # Create lock file to prevent other scripts from
 # accessing DHT22 while we poll it
-logThis "Create lock file for DHT22."
-${SH_TOUCH} $dht22LockFile
+#
+	[ $(${SH_TOUCH} $dht22LockFile & > /dev/null) ] && err "1" "$dht22LockFile" "$FUNCNAME" || logThis "Lock file $dht22LockFile created." "D" "$FUNCNAME"
+#
+	logThis "Querying the source..." "T"
+	sourceData=$(/usr/local/sbin/DHTXXD-exec)
+	sourceStatus=$(${SH_ECHO} "$sourceData"|${SH_CUT} -d ' ' -f 1)
+	# debugging. Set sourceStatus NOT EQUAL to 0 for error handling to take place...
+	#sourceStatus=3
+	logThis "Read status from DHT22: $sourceStatus."
 
-/usr/local/sbin/DHTXXD-exec
+	i=1
+	maxWaits=3
 
-${SH_SLEEP} $sleep
-${SH_RM} -f $dht22LockFile
-logThis "Remove lock file for DHT22."
-
+	while [ "$sourceStatus" -ne "0" ]; do
+		logThis "Read status: error. Retrying read [$i/$maxWaits], wait for $sleep secs between reads..." "T"
+		${SH_SLEEP} $sleep
+		sourceData=$(/usr/local/sbin/DHTXXD-exec)
+		sourceStatus=$(${SH_ECHO} "$sourceData"|${SH_CUT} -d ' ' -f 1)
+#		sourceStatus=3
+		logThis "Read status from DHT22: $sourceStatus."
+		(( i++ ))
+		if [ "$i" -eq "$maxWaits" ]; then
+			logThis "Too many read errors. This will result in error but we need to remove the DHT22 lock file before that so others can have a try at reading DHT22 too."
+			removeLock
+			#[ $(${SH_RM} -f $dht22LockFile & > /dev/null) ] && err "2" "$dht22LockFile" || logThis "Lock file $dht22LockFile removed." "D"
+			err 19 "$myNameIs" "$i"
+			break
+		fi
+	done
+	${SH_ECHO} $sourceData
+	logThis "Result from source [raw]: $sourceData" "I"
+	logThis "Wait for $sleep secs between reads..." "T"
+	${SH_SLEEP} $sleep
+	removeLock
+	#[ $(${SH_RM} -f $dht22LockFile & > /dev/null) ] && err "2" "$dht22LockFile" || logThis "Lock file $dht22LockFile removed." "D"
 #
 #################################
 
diff --git a/temperature-monitor b/temperature-monitor
--- a/temperature-monitor
+++ b/temperature-monitor
@@ -103,7 +103,6 @@ strtTme=$(date +%s.%N)
 		tempLowLimit=$1
 	fi
 #
-
 	sleep="1.5"
 	maxIters=10
 	res="0"
@@ -131,40 +130,41 @@ strtTme=$(date +%s.%N)
 #[ -z "$1" ] && usage
 #[ something "$1" ] || err "1" "$1"
 
-tempRaw=$(${SH_GREP} "t=" $mySensor1/w1_slave|${SH_CUT} -d "=" -f 2)
-#in=$(getDHTread "temp")
+#tempRaw=$(${SH_GREP} "t=" $mySensor1/w1_slave|${SH_CUT} -d "=" -f 2)
+logThis "Querying the DHT22..." "T"
+in=$(getDHTread "temp")
 
-i=0
-DHT22raw=$(${SH_DHT})
-inStatus=$(${SH_ECHO} "$DHT22raw"|${SH_CUT} -d " " -f 1)
-in=$(${SH_ECHO} "$DHT22raw"|${SH_CUT} -d " " -f 2)
-#logThis "inStatus: $inStatus, in: $in"
+#inStatus=$(${SH_ECHO} "$DHT22raw" |${SH_CUT} -d " " -f 1)
+#in=$(${SH_ECHO} "$DHT22raw"|${SH_CUT} -d " " -f 2)
+#hum=$(${SH_ECHO} "$DHT22raw"|${SH_CUT} -d " " -f 3)
+#logThis "Statuses read from source: $DHT22raw." "D"
+#logThis "Human readable statuses read from source: $inStatus. Temperature: $in"$'\xc2\xb0'"C. Humidity: $hum%." "D"
 
-while [ "$inStatus" -ne "0" ]; do
-	if [ "$i" -eq "$maxIters" ]; then
-		loggingTmp=$logging
-		logging=1
-		iterSecs=$(echo "scale=0; ($i*$sleep)/1"|bc -l)
-		err 19 "stat: $inStatus, read: $in"
-		#logThis "Read error from DHT22. Error count: $i of $maxIters [$iterSecs sec(s)]). Got result (\$in) '$in', (\$inStatus) '$inStatus'." "W"
-		logging=$loggingTmp
-		break
-		exit 1
-	fi
-
-	if [ "$inStatus" -ge "0" ]; then
-		${SH_SLEEP} $sleep
-	else
-		break
-		exit 1
-	fi
+#while [ "$inStatus" -ne "0" ]; do
+#	if [ "$i" -eq "$maxIters" ]; then
+#		loggingTmp=$logging
+#		logging=1
+#		iterSecs=$(echo "scale=0; ($i*$sleep)/1"|bc -l)
+#		err 19 "stat: $inStatus, read: $in"
+#		logThis "Read error from DHT22. Error count: $i of $maxIters [$iterSecs sec(s)]). Got result (\$in) '$in', (\$inStatus) '$inStatus'." "T"
+#		logging=$loggingTmp
+#		exit 1
+#	else
+#		logThis "Recovered read error from DHT22. Error count: $i of $maxIters [$iterSecs sec(s)]). Got result (\$in) '$in', (\$inStatus) '$inStatus'." "D"
+#	fi
+#
+#	if [ "$inStatus" -ge "0" ]; then
+#		${SH_SLEEP} $sleep
+#	else
+#		exit 1
+#	fi
 #	in=$(${SH_DHT}|${SH_CUT} -d " " -f 2)
-	DHT22raw=$(${SH_DHT})
-	inStatus=$(${SH_ECHO} "$DHT22raw"|${SH_CUT} -d " " -f 1)
-	in=$(${SH_ECHO} "$DHT22raw"|${SH_CUT} -d " " -f 2)
-	logThis "Read error from DHT22 recovered; stat: $inStatus, read: $in"
-	(( i++ ))
-done
+#	DHT22raw=$(${SH_DHT})
+#	inStatus=$(${SH_ECHO} "$DHT22raw"|${SH_CUT} -d " " -f 1)
+#	in=$(${SH_ECHO} "$DHT22raw"|${SH_CUT} -d " " -f 2)
+#	logThis "Read error from DHT22 recovered; stat: $inStatus, read: $in"
+#	(( i++ ))
+#done
 
 if [ $(${SH_ECHO} "$in>$tempLowLimit" | bc) -eq 0 ]; then
 	logThis "Temperature is below $tempLowLimit"$'\xc2\xb0'"C ($in"$'\xc2\xb0'"C)!"
@@ -191,19 +191,19 @@ elif [ -e "$trckErr" ]; then
 		exit 0
 	else
 		msg="Temperature has recovered and is now: $in"$'\xc2\xb0'"C. This however is nothing new. I will not notify anyone of this. See: $trckErr"
-		[ "$debug" -gt "0" ] && logThis "$msg"
+		logThis "$msg" "D"
 		# see above: we need to kill the script here and now.
 		# exit 0
 	fi
 else
 	msg="Temperature is above the notify treshold limit of $tempRecoveryLimit"$'\xc2\xb0'"C: $in"$'\xc2\xb0'"C)! No previous notification? Then this is not a recovery and no notification should be sent this time, either. [Based on existing '$trckErr' file.]"
-	[ "$debug" -gt "0" ] && logThis "$msg"
+	logThis "$msg" "D"
 fi
 
 msg="Temperature (in): $in"$'\xc2\xb0'"C."
-#${SH_ECHO} "My limits are low: $tempLowLimit"$'\xc2\xb0'"C and recovery: $tempRecoveryLimit"$'\xc2\xb0'"C!"
+logThis "My limits are low: $tempLowLimit"$'\xc2\xb0'"C and recovery: $tempRecoveryLimit"$'\xc2\xb0'"C!" "T"
 #${SH_ECHO} $msg
-logThis "$msg"
+logThis "$msg [Alert threshold $tempLowLimit"$'\xc2\xb0'"C]" "I"
 #################################
 #
 # End the script
diff --git a/temperature_sensor b/temperature_sensor
--- a/temperature_sensor
+++ b/temperature_sensor
@@ -3,9 +3,9 @@ strtTme=$(date +%s.%N)
 
 #################################
 #
-#  version: 0.0.1.0001
+#  version: 0.0.1.0011
 #  date: 19.07.2018
-#  mod': 03.02.2018
+#  mod': 11.02.2018
 #  Copyright Tommi Nikkilae 2018-2019
 #  url: http://f8.oire.fi/blog (techy things)
 #  url: http://f8.oire.fi/ (my photos)
@@ -44,11 +44,11 @@ strtTme=$(date +%s.%N)
 #
 #  Common variables
 #
-#  for debugging, use 1 (or '--test')
+#  for debugging, use 1
 #  for production, use 0
 #  Default is '0'
 	debug=0
-	logging=1
+	logging=5
 #
 #  ALL common configurations
 #  and functions, etc. go to:
@@ -56,7 +56,8 @@ strtTme=$(date +%s.%N)
 #  /usr/local/etc/common.cfg
 #
 	myPathIs=${0%/*}
-	. "$myPathIs/etc/common.cfg"
+#	myPathIs="/usr/local"
+	. "$myPathIs/etc/common.cfg" || echo "Error loading common files..."
 #
 #  If you want errors to kill the script, use
 	errKills=1
@@ -75,8 +76,7 @@ strtTme=$(date +%s.%N)
 #  found, the script will err() (and usually die() if errKills is set to
 #  > 0.
 #
-#	checkDep "/usr/lib/libpigpiod_if2.so"
-	checkDep "/sys/bus/w1/devices/28-03170422eaff"
+	checkDep "/usr/lib/libpigpiod_if2.so"
 #
 #  Dependencies check end
 #
@@ -90,24 +90,24 @@ strtTme=$(date +%s.%N)
 #
 #  Define the minimum time between push notifications
 #
-	minNotifyIntervalInMinutes=30
+	minNotifyIntervalInMinutes=1
 #
 #################################
 
 #################################
 #
 #  Set some more variables here if needed
+#
 #	myVar1=foo
 #	myVar2="Lorem ipsum."
 #
-#	Obsoleted here, see etc/conf/
+	OID=".1.3.6.1.2.1.25.1.11.1"
+	res="0"
+	mySensor1="/sys/bus/w1/devices/28-03170422eaff"
 #
-#	tempOutFile="/tmp/tempOut.txt"
-#	tempKanalaFile="/tmp/tempKanala.txt"
-#	humKanalaFile="/tmp/humKanala.txt"
-#	OID=".1.3.6.1.2.1.25.1.11.1"
-#	res="0"
-#	mySensor1="/sys/bus/w1/devices/28-03170422eaff"
+	tempOutFile="/tmp/tempOut.txt"
+	tempKanalaFile="/tmp/tempKanala.txt"
+	humKanalaFile="/tmp/humKanala.txt"
 #
 #################################
 
@@ -119,74 +119,107 @@ strtTme=$(date +%s.%N)
 #
 #################################
 
+#################################
+#
+#  Run trace for common variables so that they are logged with their current values.
+#
+#  traceVars
+#
+#################################
+
 # If no parameter given print
 # usage instructions for client
-	[ -z "$1" ] && usage
+	if [ -z "$1" ]; then
+		logThis "No parameters given, unable to continue." "C"
+		usage
+	fi
 
 #################################
 #
 # Actual code part goes here...
 #
-${SH_TOUCH} $tempOutFile
-${SH_TOUCH} $tempKanalaFile
-${SH_TOUCH} $humKanalaFile
+	${SH_TOUCH} $tempOutFile
+	${SH_TOUCH} $tempKanalaFile
+	${SH_TOUCH} $humKanalaFile
 
-[ -z "$1" ] && usage
+	[ -f "$tempOutFile" ] && [ "$(stat -c %a "$tempOutFile")" -ne "777" ] && chmod 777 "$tempOutFile"
+	[ -f "$tempKanalaFile" ] && [ "$(stat -c %a "$tempKanalaFile")" -ne "777" ] && chmod 777 "$tempKanalaFile"
+	[ -f "$humKanalaFile" ] && [ "$(stat -c %a "$humKanalaFile")" -ne "777" ] && chmod 777 "$humKanalaFile"
 
-case $1 in
-	-out )
-		tempRaw=$(${SH_GREP} "t=" $mySensor1/w1_slave|${SH_CUT} -d "=" -f 2)
-		OID=".1.3.6.1.2.1.25.2.11"
+	case $1 in
+		-out )
+			tempRaw=$(${SH_GREP} "t=" $mySensor1/w1_slave|${SH_CUT} -d "=" -f 2)
+			OID=".1.3.6.1.2.1.25.2.11"
 
-		z=$(${SH_ECHO} "scale=1;$tempRaw/1000" | bc -l)
+			z=$(${SH_ECHO} "scale=1;$tempRaw/1000" | bc -l)
 
-		[ -w "$tempOutFile" ] && ${SH_ECHO} $z > $tempOutFile || logThis "$tempOutFile not writable"
+			[ -w "$tempOutFile" ] && ${SH_ECHO} "$z" > $tempOutFile || logThis "$tempOutFile not writable" "D"
 
-		${SH_ECHO} $OID
-#		${SH_ECHO} "GAUGE"
-		${SH_ECHO} "INTEGER"
-		${SH_ECHO} $tempRaw
+			${SH_ECHO} $OID
+#			type="GAUGE"
+			type="INTEGER"
+			${SH_ECHO} "$type"
+			${SH_ECHO} "$tempRaw"
 
-		title="DS18B20"
-		msg="$title: Temperature: $z"$'\xc2\xb0'"C [data for SNMP poller: $tempRaw]"
-	;;
-	-in )
-		z=$(getDHTread "temp")
-#		zTMP=$(getDHTread "temp")
-#		z=round "$zTMP" "1"
-		OID=".1.3.6.1.2.1.25.1.11.1"
+			title="DS18B20"
+			msg="$title: Temperature: $z"$'\xc2\xb0'"C [data for SNMP poller: $tempRaw]"
+			logThis "$msg" "T"
+			logThis "snmp answer: $OID $type = $tempRaw" "D"
+			;;
+		-in|-hum )
+		# This is here until we get our /usr/local/sbin/DHTXXD to function properly...
+		#SH_DHT="/usr/local/sbin/DHTXXD-exec"
+		#SH_DHT="/usr/local/sbin/DHTXXD"
 
-		${SH_ECHO} $OID
-#		${SH_ECHO} "GAUGE"
-		${SH_ECHO} "INTEGER"
-		${SH_ECHO} $z| ${SH_AWK} '{print int($1+0.5)}'
+			logThis "DHT22 called" "T"
+			case $1 in
+				"-hum" )
+					srcRd="hum"
+					#OID=".1.3.6.1.2.1.25.5.10.0"
+					OID=".1.3.6.1.2.1.25.5.11"
+					;;
 
-		res=$(${SH_ECHO} "scale=1;$z/10" | bc -l)
-		[ -w "$tempKanalaFile" ] && ${SH_ECHO} $res > $tempKanalaFile || logThis "$tempKanalaFile not writable"
+				"-in" )
+					srcRd="temp"
+					#OID=".1.3.6.1.2.1.25.1.10.0"
+					OID=".1.3.6.1.2.1.25.1.11"
+					;;
 
-		title="DHT22"
-		msg="$title: Temperature: $res"$'\xc2\xb0'"C [data for SNMP poller: $z]"
+				* )
+					srcRd="temp"
+					OID=".1.0.0.0.0.0.0.0.0.0"
+					;;
+			esac
+			logThis "Querying DHT22 ($srcRd) from getDHTread()..." "T"
+			res=$(getDHTread "$srcRd")
+			logThis "Result: $res" "T"
+#			res=$(${SH_DHT}|${SH_CUT} -d " " -f 2)
+			z=$(${SH_ECHO} "scale=0;$(${SH_ECHO} $res)*100/10" | bc -l)
+			logThis "Result modified to: $res" "T"
+#			z=round "$zTMP" "1"
 
-		;;
-	-hum )
-		z=$(getDHTread "hum")
-		OID=".1.3.6.1.2.1.25.5.11.1"
+			${SH_ECHO} $OID
+#			type="GAUGE"
+			type="INTEGER"
+			${SH_ECHO} $type
+			finalRes=$(${SH_ECHO} $z| ${SH_AWK} '{print int($1+0.5)}')
+			logThis "\$z [$z] converted to \$finalRes '$finalRes'" "T"
+			${SH_ECHO} -e "$finalRes\n"
+			logThis "snmp answer: $OID $type = $finalRes" "D"
 
-		${SH_ECHO} $OID
-		${SH_ECHO} "GAUGE"
-		${SH_ECHO} $z| ${SH_AWK} '{print int($1+0.5)}'
+			res=$(${SH_ECHO} "scale=1;$z/10" | bc -l)
+			[ -w "$tempKanalaFile" ] && ${SH_ECHO} $res > $tempKanalaFile || logThis "$tempKanalaFile not writable" "D"
 
-		res=$(${SH_ECHO} "scale=1;$z/10" | bc -l)
-		[ -w "$humKanalaFile" ] && ${SH_ECHO} $res > $humKanalaFile || logThis "$humKanalaFile not writable"
+			title="DHT22"
+			msg="$title: Temperature: $res"$'\xc2\xb0'"C [data for SNMP poller: $z]"
+			logThis "$msg" "T"
+			logThis "DHT22 poll over."
+			;;
 
-		title="DHT22"
-		msg="$title: Humidity: $res% [data for SNMP poller: $z]"
-		;;
-
-	* )
-		usage
-esac
-
+		* )
+			usage
+			;;
+	esac
 #
 #################################
 
@@ -194,6 +227,6 @@ esac
 #
 # End the script
 #
-	scriptEnd
+scriptEnd
 #
 #################################
